parameters:
  datalake:
    base_path: 'dbfs:/daipe-bad-practices'

  datalakebundle:
    table:
      name_template: '%kernel.environment%_{identifier}'
      defaults:
        base_path: '%datalake.base_path%' # from config.yaml
        target_path: !expr 'base_path + "/" + db_identifier + "/" + table_identifier + ".delta"'

  paths:
    raw:
      custom_attrs: "%datalake.base_path%/bronze/raw/custom_attrs"

  datasets:
    - id: "123"
      name: "knihydobrovsky_cz"
      custom_attrs:
        ext_id: custom_1
        ga_id: custom_3
        adform_id: custom_2
    - id: "4564"
      name: "knihomol_cz"
      custom_attrs:
        ga_id: custom_2
        ext_id: custom_3
